CREATE TABLE EMPLOYEES (
	EMP_ID NUMBER(8) CONSTRAINT PK_EMP PRIMARY KEY,
	DEPT_ID NUMBER(8),
	EMP_FIRSTNAME VARCHAR(50),
	EMP_LASTNAME VARCHAR(50),
	EMP_EMAIL VARCHAR(50),
	EMP_USERNAME VARCHAR(50),
	EMP_PASS VARCHAR(50)
);


INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (1, 3, 'Jock', 'Summerside', 'jsummerside0@theatlantic.com', 'jsummerside0', '6VVJt20SJHB');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (2, 1, 'Jermaine', 'Mathys', 'jmathys1@tumblr.com', 'jmathys1', 'difObR9lvQe');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (3, 5, 'Ernie', 'Maevela', 'emaevela2@berkeley.edu', 'emaevela2', '1QfCJRxQJV');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (4, 2, 'D.J.', 'Valentine', 'flamethrower@2kGod.hoops', 'greenb3an', 'Buck4ts');

SAVEPOINT EMPLOYEE_TABLE;
COMMIT;

CREATE TABLE DEPARTMENTS (
    DEPT_ID NUMBER(8) CONSTRAINT PK_DEPT PRIMARY KEY,
    DEPT_NAME VARCHAR2(30),
    DEPT_MANG NUMBER(8) CONSTRAINT FK_DEPT_MANG REFERENCES EMPLOYEES   
);


INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (5, 1, 'Earl', 'Brekonridge', 'ebrekonridge0@yahoo.co.jp', 'ebrekonridge0', 'vn1KZd');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (6, 4, 'Carline', 'Petasch', 'cpetasch1@webs.com', 'cpetasch1', 'sAxJQHZs0LW5');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (7, 3, 'Maurise', 'Tizzard', 'mtizzard2@youtube.com', 'mtizzard2', '3pET1qCUXN');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (8, 2, 'Ariadne', 'Ough', 'aough3@examiner.com', 'aough3', 'angEWs');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (9, 5, 'Dougie', 'Lahy', 'dlahy4@gov.uk', 'dlahy4', 'o4y2GmaF4');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (10, 1, 'Phyllys', 'Southan', 'psouthan5@youku.com', 'psouthan5', 'R6uSJQdu');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (11, 2, 'Isidor', 'Coppens', 'icoppens6@vistaprint.com', 'icoppens6', 'VLQ3OT9Ce');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (12, 3, 'Bird', 'Greatrakes', 'bgreatrakes7@slashdot.org', 'bgreatrakes7', 'kpXT4fKaw');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (13, 5, 'Trudey', 'Collingworth', 'tcollingworth8@tinypic.com', 'tcollingworth8', 'c6ncGvvQy');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (14, 2, 'Marget', 'Bloxland', 'mbloxland9@ycombinator.com', 'mbloxland9', 'vlYdX5sW');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (15, 4, 'Gayler', 'Deakin', 'gdeakina@hc360.com', 'gdeakina', 'mdmLISiZK3k');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (16, 4, 'Idalia', 'Spittles', 'ispittlesb@yale.edu', 'ispittlesb', 'ix6zanAGNPf9');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (17, 1, 'Rem', 'Kubach', 'rkubachc@cbslocal.com', 'rkubachc', 'IrKYlJXgVxZx');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (18, 3, 'Alyssa', 'Wilsone', 'awilsoned@bloomberg.com', 'awilsoned', '5NqOP5');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (19, 3, 'Johannes', 'Nestle', 'jnestlee@wiley.com', 'jnestlee', 'LtA5Ox2T');
INSERT INTO EMPLOYEES (EMP_ID, DEPT_ID, EMP_FIRSTNAME, EMP_LASTNAME, EMP_EMAIL, EMP_USERNAME, EMP_PASS) VALUES (20, 5, 'Erie', 'Clewlowe', 'eclewlowef@canalblog.com', 'eclewlowef', 'kMwoQDFkW');

INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_MANG) VALUES (1, 'Human Resources', 13);
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_MANG) VALUES (2, 'Information Technology', 11);
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_MANG) VALUES (3, 'Marketing', 4);
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_MANG) VALUES (4, 'Accounting', 18);
INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_MANG) VALUES (5, 'Engineering', 2);

SAVEPOINT EMPLOYEESANDDEPARTMENTS;
COMMIT;

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_DEPT_ID
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID);

COMMIT;