CREATE SEQUENCE EMP_ID_SEQ
START WITH 10100
INCREMENT BY 1
NOCYCLE;
CREATE SEQUENCE TRANS_ID_SEQ
START WITH 30300
INCREMENT BY 1
NOCYCLE;
CREATE TABLE EMPLOYEE(
  E_ID NUMBER PRIMARY KEY,
  IS_MANAGER CHAR(1) NOT NULL,
  F_NAME VARCHAR2(15),
  L_NAME VARCHAR2(18),
  PHONE VARCHAR2(12),
  EMAIL VARCHAR2(40) UNIQUE NOT NULL,
  PASSWD VARCHAR2(30)
);
CREATE TABLE REIMBURSEMENT(
    T_ID NUMBER UNIQUE,
    E_ID CONSTRAINT FK_TRANS_EMP REFERENCES EMPLOYEE,
    T_OPTION VARCHAR2(15) DEFAULT NULL,
    REQCOM VARCHAR2(280) DEFAULT NULL,
    RESCOM VARCHAR2(280) DEFAULT NULL,
    R_AMOUNT NUMBER(10,2) NOT NULL,
    S_STATUS VARCHAR2(9) NOT NULL,
    SUB_DATE DATE NOT NULL,
    DEC_DATE DATE DEFAULT NULL,
    M_ID NUMBER DEFAULT NULL
);

INSERT INTO EMPLOYEE VALUES (EMP_ID_SEQ.NEXTVAL,'N', 'Chris', 'Kyle', '114-112-1134', 'ck@aol.com', 'pass');
INSERT INTO EMPLOYEE VALUES (EMP_ID_SEQ.NEXTVAL,'Y', 'Peyton', 'Riley', '111-111-1111', 'prsm@aol.com', 'pass');
SELECT * FROM EMPLOYEE;
commit;
UPDATE EMPLOYEE SET EMAIL = NVL(NULL,EMAIL) WHERE E_ID = 10100;
INSERT INTO REIMBURSEMENT VALUES (TRANS_ID_SEQ.NEXTVAL,10140,'TRAVEL', NULL, NULL, 100.09,'PENDING', DATE '2019-03-14', NULL,NULL);
SELECT * FROM REIMBURSEMENT;

