--CREATE INVOICE TABLE
CREATE TABLE INVOICE(
    INV_ID NUMBER(5),
    INV_DATE DATE,
    CUSTOMER_ID NUMBER(5),
    AMOUNT NUMBER(5,2)
);

--CREATE CUSTOMER TABLE
CREATE TABLE CUSTOMER(
    CUSTOMER_ID NUMBER(5),
    CUSTOMER_NAME VARCHAR2(50)
);

--ADD PRIMARY KEY IN CUSTOMER TABLE
ALTER TABLE CUSTOMER 
ADD CONSTRAINT PK_CUST PRIMARY KEY(CUSTOMER_ID);

--ADD REFERENCE IN INVOICE TABLE TO CUSTOMER TABLE
ALTER TABLE INVOICE
ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);

--INSERT 10 RECORDS INTO INVOCE TABLE
INSERT INTO INVOICE VALUES(1, DATE '2018-10-12', 3, 47.00);
INSERT INTO INVOICE VALUES(2, DATE '2018-12-03', 1, 22.75);
INSERT INTO INVOICE VALUES(3, DATE '2018-12-22', 2, 74.50);
INSERT INTO INVOICE VALUES(4, DATE '2019-01-01', 3, 32.20);
INSERT INTO INVOICE VALUES(5, DATE '2019-01-12', 4, 104.00);
INSERT INTO INVOICE VALUES(6, DATE '2019-02-22', 2, 13.04);
INSERT INTO INVOICE VALUES(7, DATE '2019-02-14', 1, 9.01);
INSERT INTO INVOICE VALUES(8, DATE '2019-02-24', 5, 46.00);
INSERT INTO INVOICE VALUES(9, DATE '2018-11-10', 2, 10.43);
INSERT INTO INVOICE VALUES(10, DATE '2019-02-26', 5, 31.44);
insert into invoice values(11, date '2019-01-20', 3, 19.94);

--INSERT 5 RECORDS INTO CUSTOMER TABLE
INSERT INTO CUSTOMER VALUES(1, 'FRED NIETCHE');
INSERT INTO CUSTOMER VALUES(2, 'BILL DOH');
INSERT INTO CUSTOMER VALUES(3, 'TED SOUTH');
INSERT INTO CUSTOMER VALUES(4, 'MARY JOSEPH');
INSERT INTO CUSTOMER VALUES(5, 'SUSAN PARKER');

--UPDATE AND DELETE VARIOUS RECORDS
UPDATE INVOICE 
SET CUSTOMER_ID = 4 
WHERE INV_ID = 6;

UPDATE INVOICE
SET INV_DATE = DATE '2018-12-25'
WHERE INV_ID = 9;

DELETE FROM INVOICE 
WHERE INV_ID = 4;

--SHOW PURCHASES THAT OCCURED TODAY
SELECT * 
FROM INVOICE 
WHERE inv_date = DATE '2019-02-26';

--SHOW EACH CUSTOMER AND NUMBER OF THEIR PURCHASES
select customer.customer_name, count(invoice.inv_id)
from customer, invoice
where invoice.customer_id = customer.customer_id
group by customer.customer_name;

--SHOW EACH CUSTOMER AND THEIR TOTAL COST OF PURCHASES
select customer.customer_name, sum(invoice.amount)
from customer, invoice
where invoice.customer_id = customer.customer_id
group by customer.customer_name;

--SHOW ALL PURCHASES FROM THE LAST MONTH IN DECENDING ORDER
select * 
from invoice
where inv_date < date '2019-01-26' and inv_date > date '2018-12-26'
order by inv_date desc;

--SHOW TOP THREE MOST EXPENSIVE PURCHASES
select *
from invoice
order by amount desc
fetch next 3 rows only;