server:
  port: 3333

spring:
  application:
    name: employee-service

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      default: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 3

feign:
  hystrix:
    enabled: true
