### server.port=8761
### ^ what we've seen in properties files 

server:
  port: 8761
  
spring:
  application:
    name: eureka
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false