CREATE TABLE C_USERS(
CUSTOMER_ID NUMBER(3) PRIMARY KEY,
CUSTOMER_NAME VARCHAR2(25),
BALANCE NUMBER(9,2),
USERNAME VARCHAR2(25),
PASSWORD VARCHAR2(25)
);

ALTER TABLE C_USERS
MODIFY CUSTOMER_ID NUMBER;

ALTER TABLE C_USERS
MODIFY BALANCE NUMBER;