DROP TABLE EMPLOYEE;
DROP TABLE MANAGERS;
DROP TABLE REIMBURSEMENTS;


CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID NUMBER(5) PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
    EMPLOYEE_EMAIL VARCHAR(25),
	TITLE VARCHAR(50),
	MANAGERS_ID NUMBER (5)
);

CREATE TABLE MANAGERS (
	MANAGERS_ID NUMBER (5),
	EMPLOYEE_ID NUMBER (5)
);

CREATE TABLE REIMBURSEMENTS
(
    REIMBURSEMENT_ID NUMBER(10) PRIMARY KEY,
    REIMBURSEMENT_AMOUNT NUMBER(12,2) NOT NULL,
    REIMBURSENEBT_STATUS NUMBER(1) DEFAULT 0 NOT NULL,
    REIMBURSEMENT_DATE TIMESTAMP NOT NULL,
    REIMBURSEMENT_DESC VARCHAR2(200),
    REIMBURSEMENT_RECEIPT BLOB,
    MANAGERS_ID NUMBER(5),
    EMPLOYEE_ID NUMBER(10) NOT NULL
);
