SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMPLOYEE_EMAIL, TITLE FROM EMPLOYEE WHERE EMPLOYEE_ID = 1

SELECT * FROM EMPLOYEE WHERE EMPLOYEE_EMAIL = 'fake4@gmail.com';

SELECT * FROM REIMBURSEMENTS INNER JOIN EMPLOYEE ON REIMBURSEMENTS.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID WHERE EMPLOYEE.EMPLOYEE_EMAIL = 'fake10@gmail.com'

INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, EMPLOYEE_EMAIL, EMPLOYEE_PASSWORD, TITLE, MANAGERS_ID) VALUES('JON', 'd', '5@GMAIL.COM', 1111, 'GENERIC', 4);

UPDATE EMPLOYEE 
SET FIRST_NAME = 'JILL', LAST_NAME = 'DOE', EMPLOYEE_EMAIL = 'girl@gmail.com', EMPLOYEE_PASSWORD = 2222, TITLE = 'NONGENERIC'
WHERE EMPLOYEE_ID = 14;

INSERT INTO 


DELETE * FROM REIMBURSEMENTS WHERE REIMBURSEMENT_ID = 16;



INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, EMPLOYEE_EMAIL, EMPLOYEE_PASSWORD) VALUES('JON', 'd', '5@GMAIL.COM', 'newpass');
INSERT INTO REIMBURSEMENTS (REIMBURSEMENT_AMOUNT, REIMBURSEMENT_DESC, EMPLOYEE_ID) VALUES(50, 'test1', 77877);