--2.1 SELECT--

--A
SELECT * FROM CHINOOK.EMPLOYEE;

--B
SELECT * FROM CHINOOK.EMPLOYEE CE
WHERE CE.LASTNAME = 'King';

--C
SELECT * FROM CHINOOK.EMPLOYEE CE
WHERE CE.FIRSTNAME = 'Andrew'
AND CE.REPORTSTO IS NULL;

--D
SELECT * FROM CHINOOK.ALBUM CA
ORDER BY CA.TITLE DESC;

--E
SELECT CC.FIRSTNAME FROM CHINOOK.CUSTOMER CC
ORDER BY CC.CITY;

--F
SELECT * FROM CHINOOK.INVOICE CI
WHERE SUBSTR(CI.BILLINGADDRESS, 1, 1) = 'T';

--2.2 INSERT INTO--

--A
INSERT INTO CHINOOK.GENRE VALUES (1000, 'Gorecore');
INSERT INTO CHINOOK.GENRE VALUES (1001, 'Nightcore');

--B


