--CLEAN BEFORE RUN
DROP TABLE INVOICE;
DROP TABLE CUSTOMER;

--CREATE CUSTOMER TABLE
CREATE TABLE CUSTOMER(
    C_ID NUMBER(5) CONSTRAINT C_PK PRIMARY KEY,
    C_NAME VARCHAR2(50) NOT NULL,
    C_AGE NUMBER(3) NOT NULL
);

--CREATE INVOICE TABLE
CREATE TABLE INVOICE(
    INV_ID NUMBER(5) PRIMARY KEY,
    INV_DATE DATE NOT NULL,
    C_ID NUMBER(5) CONSTRAINT I_FK REFERENCES CUSTOMER,
    INV_AMOUNT NUMBER(5, 2) NOT NULL
);

--ADD 5 CUSTOMERS
INSERT INTO CUSTOMER VALUES (1, 'David', 25);
INSERT INTO CUSTOMER VALUES (2, 'Mark', 15);
INSERT INTO CUSTOMER VALUES (3, 'Kyle', 36);
INSERT INTO CUSTOMER VALUES (4, 'Klein', 53);
INSERT INTO CUSTOMER VALUES (7, 'Watson', 68);

--ADD 10 INVOICES
INSERT INTO INVOICE VALUES(1, DATE'2002-1-22', 1, 100);
INSERT INTO INVOICE VALUES(2, DATE'2019-1-27', 2, 278.23);
INSERT INTO INVOICE VALUES(3, DATE'2019-2-27', 2, 50.64);
INSERT INTO INVOICE VALUES(4, DATE'2019-1-22', NULL, 39.67);
INSERT INTO INVOICE VALUES(5, DATE'2019-1-28', 4, 999.24);
--INSERT INTO INVOICE VALUES(6, DATE'2019-1-29', 5, 645.12);
INSERT INTO INVOICE VALUES(7, DATE'2007-2-22', NULL, 234.54);
INSERT INTO INVOICE VALUES(8, DATE'2006-1-22', 3, 1.65);
--INSERT INTO INVOICE VALUES(9, DATE'2019-2-10', 5, 283.32);
INSERT INTO INVOICE VALUES(10, DATE'2019-1-27', 4, 5.60);

--CHECK IF TABLES ARE CORRECT
SELECT * FROM INVOICE;
SELECT * FROM CUSTOMER;

--UPDATE THE FIRST INVOICE AND CHECK
UPDATE INVOICE
SET INV_AMOUNT = 865.32
WHERE INV_ID = 1;

SELECT * FROM INVOICE;

--DELETE LAST INVOICE AND CHECK
DELETE FROM INVOICE
WHERE INV_ID = 10;

SELECT * FROM INVOICE;

--SHOWING PURCHASES MADE TODAY
SELECT INV_AMOUNT AS PURCHASES
FROM INVOICE
WHERE INV_DATE = TRUNC(SYSDATE);

--SHOWING CUSTOMER # OF PURCHASES
SELECT C_ID, COUNT(C_ID)
FROM INVOICE
GROUP BY C_ID;

--SHOWING CUSTOMER AND THEIR TOTAL PURCHASE
SELECT C_ID AS CUSTOMER, SUM(INV_AMOUNT) AS AMOUNT
FROM INVOICE
GROUP BY C_ID
ORDER BY C_ID ASC;

--SHOWING ALL PURCHASES MADE LAST MONTH IN DESC
SELECT INV_AMOUNT, INV_DATE
FROM INVOICE
WHERE INV_DATE
BETWEEN ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1) 
AND LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE,'MM'), -1))
GROUP BY INV_AMOUNT, INV_DATE
ORDER BY EXTRACT(DAY FROM INV_DATE) DESC;

--SHOWING TOP THREE EXPENSIVE PURCHASES
SELECT INV_AMOUNT AS AMOUNT
FROM INVOICE
ORDER BY INV_AMOUNT DESC
FETCH FIRST 3 ROWS ONLY;  

--WORKING WITH JOINS

--A
SELECT * FROM INVOICE I
JOIN CUSTOMER C
ON I.C_ID = C.C_ID;
--B
SELECT * 
FROM INVOICE I
RIGHT JOIN CUSTOMER C
ON I.C_ID = C.C_ID;
--C
SELECT I.*, C.C_NAME
FROM INVOICE I 
FULL JOIN CUSTOMER C 
ON I.C_ID = C.C_ID;
--D
SELECT C.C_NAME, I.INV_AMOUNT
FROM CUSTOMER C
FULL JOIN INVOICE I
ON C.C_ID = I.C_ID;

--CHALLENGE

--A
SELECT C.*, I.iNV_DATE
FROM CUSTOMER C
JOIN INVOICE I
ON C.C_ID = I.C_ID
ORDER BY I.INV_DATE DESC
FETCH FIRST ROW ONLY;
--B






    
    