server:
  port: 9998
eureka:
  client:
    service-url:
      default:: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/agilaydones/configServer.git
      