    
server:
  port: 8765
  
spring:
  application:
    name: gateway-server
    
zuul:
  routes:
    employee:
      path: /employees/**
      serviceId: employee-service
      strip-prefix: false
    reimbursement:
      path: /reimbursements/**
      serviceId: reimbursement-service
      strip-prefix: false