ROLLBACK TO MYSAVEPOINT;


-----------------------------------------
-- SET OPERATORS
-----------------------------------------
SELECT *
FROM EMPLOYEE
WHERE EMP_ID>3
UNION
SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>2900;

SELECT *
FROM
    (SELECT *
    FROM EMPLOYEE
    WHERE EMP_ID>3
    UNION ALL
    SELECT * 
    FROM EMPLOYEE
    WHERE MONTHLY_SALARY>2900)
ORDER BY MONTHLY_SALARY;

SELECT *
FROM EMPLOYEE
WHERE EMP_ID>3
MINUS
SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>2900;


SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>2900
MINUS
SELECT *
FROM EMPLOYEE
WHERE EMP_ID>3;

SELECT *
FROM EMPLOYEE
WHERE EMP_ID>3
INTERSECT
SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>2900;


CREATE TABLE EMPLOYEE2 AS 
    SELECT EMP_ID, EMP_NAME, MONTHLY_SALARY
    FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE
WHERE EMP_ID>3
UNION
SELECT * 
FROM EMPLOYEE2
WHERE MONTHLY_SALARY>2900;


SELECT EMP_ID, EMP_NAME, MONTHLY_SALARY
FROM EMPLOYEE
WHERE EMP_ID>3
UNION
SELECT * 
FROM EMPLOYEE2
WHERE MONTHLY_SALARY>2900;

--------------------------------------------
-- WORKING WITH JOINS
--------------------------------------------

INSERT INTO EMPLOYEE VALUES (7, 'LOLA JACKSON', DATE '1993-01-06', 3000, 'MK_REP', 1, 2, DATE '2018-12-12');
INSERT INTO EMPLOYEE VALUES (8, 'NICK OAKS', DATE '1987-03-04', 1900, 'ACCOUNT', 2, 3, DATE '2017-10-11');
INSERT INTO EMPLOYEE VALUES (9, 'ANNA DEAN', DATE '1989-02-15', 3200, 'HR_COORD', NULL, NULL, DATE '2017-04-05');
INSERT INTO EMPLOYEE VALUES (10, 'HARRIET JENKINS', DATE '1990-03-04', 2200, 'HR_ASSIST', 5, NULL, DATE '2019-01-16');
COMMIT;

-- INNER JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- IMPLICIT JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_ID = D.DEPT_ID;

-- NATURAL JOIM
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
NATURAL JOIN DEPARTMENT D;

-- FULL OUTER JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
FULL JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- RIGHT OUTER JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- LEFT OUTER JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- USING AN IMPLICIT INNER JOIN TO ACCOMPLISH A SELF JOIN
SELECT E1.EMP_NAME AS EMPLOYEE, E2.EMP_NAME AS MANAGER
FROM EMPLOYEE E1, EMPLOYEE E2
WHERE E1.MANAGER_ID = E2.EMP_ID;

-- CROSS JOIN
SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE E
CROSS JOIN DEPARTMENT D;

-- FIND DEPARTMENT WITH THE MOST RECENT HIRE
SELECT D.*
FROM DEPARTMENT D
JOIN EMPLOYEE E
ON E.DEPT_ID = D.DEPT_ID
WHERE E.HIRE_DATE =
    (SELECT MAX(HIRE_DATE)
    FROM EMPLOYEE);
    
-- SUM OF EACH DEPARTMENT SALARY
SELECT D.DEPT_NAME, SUM(E.MONTHLY_SALARY) AS TOTAL
FROM DEPARTMENT D
JOIN EMPLOYEE E
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME;

-------------------------------------
-- ADDING LOCATIONS TABLE
-------------------------------------

CREATE TABLE LOCATIONS(
    LOCATION_ID NUMBER(5),
    STREET VARCHAR2(20),
    CITY VARCHAR2(20),
    STATE VARCHAR2(2),
    ZIPCODE NUMBER(5)
);
-- ADD A PRIMARY KEY
ALTER TABLE LOCATIONS
ADD CONSTRAINT PK_LOCATIONS PRIMARY KEY (LOCATION_ID);


-- MODIFY EMPLOYEE TABLE, ADDING A COLUMN FOR LOCATION
ALTER TABLE EMPLOYEE
ADD LOCATION_ID NUMBER(5);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMP_LOCATION
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS;

-- ADD LOCATIONS TO TABLE
INSERT INTO LOCATIONS VALUES (1, '14 MAIN STREET', 'RESTON','VA',20190);
INSERT INTO LOCATIONS VALUES (2, '1060 TCHOPITOULAS ST', 'NEW ORLEANS', 'LA', 70118);
INSERT INTO LOCATIONS VALUES (3, '200 LOMBARD ST', 'SAN FRANCISCO', 'CA', 94109);
COMMIT;

INSERT INTO EMPLOYEE VALUES (11, 'ARIEL PAVIS', DATE '1981-09-23', 4500.00, 'LG_LAW', NULL, 5, DATE '2015-07-12',1);
INSERT INTO EMPLOYEE VALUES (12, 'MELISSA ITZKOVSKY', DATE '1983-03-03', 3870.00, 'LG_LAW',11, 5, DATE '2014-09-15',1);
INSERT INTO EMPLOYEE VALUES (13, 'MALIA FILISOV', DATE '1976-07-11', 4620.00, 'CS_REP', NULL, 6, DATE '2014-11-09',1);
INSERT INTO EMPLOYEE VALUES (14, 'BRENDAN LOUISET', DATE '1979-01-21', 3760.00, 'CS_REP',13, 6, DATE '2018-03-28',1);
INSERT INTO EMPLOYEE VALUES (15, 'MILT KLIEMANN', DATE '1983-02-25', 3820.00, 'AC_ACCOUNT', 2, 2, DATE '2016-05-01',1);
INSERT INTO EMPLOYEE VALUES (16, 'LUCILLE HUNE', DATE '1994-01-04', 2300.00, 'MK_REP',1, 1, DATE '2016-04-17',3);
INSERT INTO EMPLOYEE VALUES (17, 'PETA POLTZOLD', DATE '1990-09-24', 2500.00, 'IT_DEV',3, 3, DATE '2015-07-10',3);
INSERT INTO EMPLOYEE VALUES (18, 'LYDIA POVER', DATE '1991-10-01', 2800.00, 'IT_DEV', 17, 3, DATE '2016-08-03',1);
INSERT INTO EMPLOYEE VALUES (19, 'RON WINTERTON', DATE '1977-09-27', 2500.00, 'LG_LAW', 11, 5, DATE '2018-02-23',2);
INSERT INTO EMPLOYEE VALUES (20, 'NITIN CHESTNUT', DATE '1995-01-18', 2800.00, 'CS_REP', 13, 6, DATE '2014-10-25',2);
INSERT INTO EMPLOYEE VALUES (21, 'JILLIAN KYND', DATE '1980-10-15', 2840.00, 'AC_ACCOUNT', 2, 2, DATE '2015-05-11',2);
INSERT INTO EMPLOYEE VALUES (22, 'TIM KIBBEL', DATE '1980-05-20', 2240.00, 'MK_REP', 1, 1, DATE '2014-07-28',2);
INSERT INTO EMPLOYEE VALUES (23, 'ETHELIN COMINI', DATE '1982-06-16', 3380.00, 'IT_DEV', 3, 3, DATE '2017-10-02',2);
INSERT INTO EMPLOYEE VALUES (24, 'JASE HANDLEY', DATE '1975-10-08', 1870.00, 'LG_LAW',11, 5, DATE '2017-08-17',3);
COMMIT;

SELECT E.EMP_NAME, L.STATE
FROM EMPLOYEE E
JOIN LOCATIONS L
ON E.LOCATION_ID = L.LOCATION_ID;

SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT, CONCAT(L.CITY, CONCAT(', ',L.STATE)) AS LOCATION
FROM EMPLOYEE E
JOIN LOCATIONS L
ON E.LOCATION_ID = L.LOCATION_ID
JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

