ROLLBACK TO MYSAVEPOINT;


-----------------------------------------
-- SET OPERATORS
-----------------------------------------
SELECT *
FROM EMPLOYEE
WHERE EMP_ID>3
UNION
SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>2900;

SELECT *
FROM
    (SELECT *
    FROM EMPLOYEE
    WHERE EMP_ID>3
    UNION ALL
    SELECT * 
    FROM EMPLOYEE
    WHERE MONTHLY_SALARY>2900)
ORDER BY MONTHLY_SALARY;

SELECT *
FROM EMPLOYEE
WHERE EMP_ID>3
MINUS
SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>2900;


SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>2900
MINUS
SELECT *
FROM EMPLOYEE
WHERE EMP_ID>3;

SELECT *
FROM EMPLOYEE
WHERE EMP_ID>3
INTERSECT
SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>2900;


CREATE TABLE EMPLOYEE2 AS 
    SELECT EMP_ID, EMP_NAME, MONTHLY_SALARY
    FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE
WHERE EMP_ID>3
UNION
SELECT * 
FROM EMPLOYEE2
WHERE MONTHLY_SALARY>2900;


SELECT EMP_ID, EMP_NAME, MONTHLY_SALARY
FROM EMPLOYEE
WHERE EMP_ID>3
UNION
SELECT * 
FROM EMPLOYEE2
WHERE MONTHLY_SALARY>2900;

--------------------------------------------
-- WORKING WITH JOINS
--------------------------------------------

INSERT INTO EMPLOYEE VALUES (7, 'LOLA JACKSON', DATE '1993-01-06', 3000, 'MK_REP', 1, 2, DATE '2018-12-12');
INSERT INTO EMPLOYEE VALUES (8, 'NICK OAKS', DATE '1987-03-04', 1900, 'ACCOUNT', 2, 3, DATE '2017-10-11');
INSERT INTO EMPLOYEE VALUES (9, 'ANNA DEAN', DATE '1989-02-15', 3200, 'HR_COORD', NULL, NULL, DATE '2017-04-05');
INSERT INTO EMPLOYEE VALUES (10, 'HARRIET JENKINS', DATE '1990-03-04', 2200, 'HR_ASSIST', 5, NULL, DATE '2019-01-16');
COMMIT;

-- INNER JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- IMPLICIT JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_ID = D.DEPT_ID;

-- NATURAL JOIM
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
NATURAL JOIN DEPARTMENT D;

-- FULL OUTER JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
FULL JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- RIGHT OUTER JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- LEFT OUTER JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- USING AN IMPLICIT INNER JOIN TO ACCOMPLISH A SELF JOIN
SELECT E1.EMP_NAME AS EMPLOYEE, E2.EMP_NAME AS MANAGER
FROM EMPLOYEE E1, EMPLOYEE E2
WHERE E1.MANAGER_ID = E2.EMP_ID;

-- CROSS JOIN
SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE E
CROSS JOIN DEPARTMENT D;
