DROP TABLE CUSTOMER;
DROP TABLE INVOICE;

CREATE TABLE CUSTOMER (
    C_ID NUMBER(5) PRIMARY KEY,
    C_NAME VARCHAR2(50),
    AGE NUMBER(3)
);

CREATE TABLE INVOICE (
    I_ID NUMBER(5) PRIMARY KEY,
    I_DATE DATE,
    C_ID NUMBER(5) REFERENCES CUSTOMER,
    AMOUNT NUMBER(5,2)
);

INSERT INTO CUSTOMER VALUES(1, 'Alfonzo Shimothy', 22);
INSERT INTO CUSTOMER VALUES(2, 'Kim Kimothy', 26);
INSERT INTO CUSTOMER VALUES(3, 'Horlop', 18);
INSERT INTO CUSTOMER VALUES(4, 'Baby McBabyface', 7);
INSERT INTO CUSTOMER VALUES(5, 'XxxNoobxxX', 37);
INSERT INTO CUSTOMER VALUES(6, 'hahamaiboi', 18);
INSERT INTO INVOICE VALUES (1, DATE'2018-08-21' , 1, 80);
INSERT INTO INVOICE VALUES (2, DATE'2019-10-10' , 1, 400);
INSERT INTO INVOICE VALUES (3, DATE'2017-02-16' , 2, 999.98);
INSERT INTO INVOICE VALUES (4, DATE'1995-02-01' , 2, 10.01);
INSERT INTO INVOICE VALUES (5, DATE'2016-05-11' , 2, 11.85);
INSERT INTO INVOICE VALUES (6, DATE'2018-08-21' , 3, 983.00);
INSERT INTO INVOICE VALUES (7, DATE'2019-12-21' , 3, 111);
INSERT INTO INVOICE VALUES (8, DATE'2019-11-02' , 4, 2.45);
INSERT INTO INVOICE VALUES (9, DATE'2019-09-18' , 4, 999.99);
INSERT INTO INVOICE VALUES (10, DATE'2019-02-26' , 5, 1.99);
INSERT INTO INVOICE VALUES (11, DATE'2019-02-22' , NULL, 22.22);

UPDATE INVOICE
SET amount = 2.99
WHERE i_id = 10;

DELETE FROM INVOICE
WHERE i_id = 9;

SELECT * 
FROM INVOICE
WHERE i_date = TRUNC(sysdate);

SELECT C_ID AS CUSTOMER, COUNT(C_ID) AS PURCHASES
FROM INVOICE
GROUP BY C_ID;

SELECT C_ID AS CUSTOMER, SUM(AMOUNT)
FROM INVOICE
GROUP BY C_ID;

SELECT AMOUNT
FROM INVOICE
ORDER BY AMOUNT DESC
FETCH FIRST 3 ROWS ONLY;

-- PART 2 --

SELECT I.*
FROM INVOICE  I
JOIN CUSTOMER C
ON I.C_ID = C.C_ID;

SELECT I.I_ID, C.C_ID
FROM INVOICE I
RIGHT JOIN CUSTOMER C
ON I.C_ID = C.C_ID;

SELECT I.I_ID, C.C_NAME
FROM INVOICE I
FULL JOIN CUSTOMER C
ON I.C_ID = C.C_ID;

SELECT C.C_NAME, SUM(I.AMOUNT)
FROM INVOICE I
RIGHT JOIN CUSTOMER C
ON I.C_ID = C.C_ID group by C.C_NAME;

SELECT C.*
FROM CUSTOMER C
JOIN INVOICE I
ON I.C_ID = C.C_ID
ORDER BY I.I_DATE DESC
FETCH FIRST 1 ROWS ONLY;

SELECT I.I_ID, C.C_NAME, I.AMOUNT * 1.06
FROM INVOICE I
JOIN CUSTOMER C
ON I.C_ID = C.C_ID
