CREATE TABLE CUSTOMER (
    C_ID NUMBER(5) CONSTRAINT PK_C PRIMARY KEY,
    C_FIRST_NAME VARCHAR2(3000 CHAR),
    C_LAST_NAME  VARCHAR2(3000 CHAR)
);

CREATE TABLE INVOICE (
    I_ID NUMBER(5) PRIMARY KEY,
    I_AMOUNT NUMBER(5, 2) NOT NULL,
    I_DATE DATE,
    C_ID  NUMBER(5) CONSTRAINT FK_I_C REFERENCES CUSTOMER
);

INSERT INTO CUSTOMER VALUES (1, 'LeBron', 'James');
INSERT INTO CUSTOMER VALUES (2, 'James', 'Harden');
INSERT INTO CUSTOMER VALUES (3, 'Kobe', 'Bryant');
INSERT INTO CUSTOMER VALUES (4, 'Jeremy', 'Lin');
INSERT INTO CUSTOMER VALUES (5, 'Kyrie', 'Irving');

INSERT INTO INVOICE VALUES (1, 20, DATE '1998-07-24', 2);
INSERT INTO INVOICE VALUES (2, 126,DATE '2014-10-12', 5);
INSERT INTO INVOICE VALUES (3, 59, DATE '2016-10-12', 2);
INSERT INTO INVOICE VALUES (4, 78, DATE '2008-04-18', 4);
INSERT INTO INVOICE VALUES (5, 48, DATE '2019-01-12', 2);
INSERT INTO INVOICE VALUES (6, 37, DATE '1992-10-12', 2);
INSERT INTO INVOICE VALUES (7, 98, DATE '2019-01-26', 5);
INSERT INTO INVOICE VALUES (8, 92, DATE '2013-10-12', 2);
INSERT INTO INVOICE VALUES (9, 17, DATE '2011-10-12', 3);
INSERT INTO INVOICE VALUES (10, 95, DATE '2015-10-12', 3);
INSERT INTO INVOICE VALUES (11, 125, DATE '2015-10-12', NULL);
INSERT INTO INVOICE VALUES (12, 187, DATE '2015-10-12', NULL);
INSERT INTO INVOICE VALUES (13, 126, DATE '2015-10-12', NULL);

UPDATE INVOICE SET I_DATE = DATE '2019-02-26' WHERE I_ID = 4;
UPDATE INVOICE SET C_ID = 1 WHERE I_ID = 5;

-- query to show purchase from today
SELECT i_amount
FROM INVOICE
WHERE I_DATE = DATE '2019-02-26';


-- query to show each CUSTOMER and the number of purchases made by each
SELECT C.C_FIRST_NAME AS FIRST_NAME, C.C_LAST_NAME AS LAST_NAME, COUNT(I.C_ID) AS PURCHASES
FROM INVOICE I
INNER JOIN CUSTOMER C
ON I.C_ID = C.C_ID
GROUP BY C.C_FIRST_NAME, C.C_LAST_NAME
ORDER BY COUNT(I.C_ID) DESC;


-- query to show each CUSTOMER and the total cost of all their purchases
SELECT C.C_FIRST_NAME AS FIRST_NAME, C.C_LAST_NAME AS LAST_NAME, SUM(I.I_AMOUNT) AS TOTAL
FROM INVOICE I
INNER JOIN CUSTOMER C
ON I.C_ID = C.C_ID
GROUP BY C.C_FIRST_NAME, C.C_LAST_NAME
ORDER BY SUM(I.I_AMOUNT) DESC;


-- query to return all the purchases which took place in the last month, dipslay in desc order
SELECT i_amount
FROM INVOICE
WHERE I_DATE BETWEEN DATE '2019-01-01' AND DATE '2019-01-31'
ORDER BY I_DATE DESC;


-- query to show the three most expensive purchases
SELECT i_amount
FROM INVOICE
ORDER BY I_AMOUNT DESC
FETCH FIRST 3 ROW ONLY;


/* 
query to returns all of the invoices which have a listed customer, but not invoices
who have no customer listed and not customers who have no invoices listed
*/
SELECT C.C_FIRST_NAME AS FIRST_NAME, C.C_LAST_NAME AS LAST_NAME, C.C_ID, I.C_ID
FROM INVOICE I
INNER JOIN CUSTOMER C
ON I.C_ID = C.C_ID
ORDER BY c.c_id;

/*
query which returns all of the invoices and their customer, 
not invoices who have no customer 
listed but include customers which have no invoices listed
*/
SELECT C.C_FIRST_NAME AS FIRST_NAME, C.C_LAST_NAME AS LAST_NAME, C.C_ID, I.C_ID
FROM INVOICE I
FULL JOIN CUSTOMER C
ON I.C_ID = C.C_ID
ORDER BY c.c_id;

/*query which shows each record in the invoice 
table, along with the name of the customer
*/
SELECT C.C_FIRST_NAME AS FIRST_NAME, C.C_LAST_NAME AS LAST_NAME, C.C_ID, I.C_ID
FROM INVOICE I
JOIN CUSTOMER C
ON I.C_ID = C.C_ID
ORDER BY c.c_id;

-- query which shows the name of each customer and the total amount they have spent
SELECT C.C_FIRST_NAME AS FIRST_NAME, C.C_LAST_NAME AS LAST_NAME, SUM(I.I_AMOUNT) AS TOTAL
FROM INVOICE I
INNER JOIN CUSTOMER C
ON I.C_ID = C.C_ID
GROUP BY C.C_FIRST_NAME, C.C_LAST_NAME
ORDER BY SUM(I.I_AMOUNT) DESC;

-- query record of the customer who made the most recent purchase
SELECT C.C_FIRST_NAME AS FIRST_NAME, C.C_LAST_NAME AS LAST_NAME, I.I_DATE AS DATEE
FROM INVOICE I
INNER JOIN CUSTOMER C
ON I.C_ID = C.C_ID
ORDER BY I.I_DATE DESC
FETCH FIRST ROW ONLY;

-- query which shows the purchaser of each invoice and 
-- the subtotal of each invoice if 6% sales tax was applied
-- to the subtotal to get the price of each invoice
SELECT C.C_FIRST_NAME AS FIRST_NAME, C.C_LAST_NAME AS LAST_NAME, 
I.I_AMOUNT AS TOTAL, (I.I_AMOUNT + (I.I_AMOUNT * 0.06)) AS AFTER_TAX_TOTAL
FROM INVOICE I
INNER JOIN CUSTOMER C
ON I.C_ID = C.C_ID
ORDER BY I.I_AMOUNT DESC





