server:
  port: 8765

spring:
  application:
    name: gateway-server
    
zuul:
  routes:
    account:
      path: /employee/**
      serviceId: employee-service
      strip-prefix: false
    customer:
      path: /reimbursement/**
      serviceId: reimbursement-service
      strip-prefix: false