#server:
#  port: 3333
#
#spring:
#  application:
#    name: emps-service
#    
#    
#eureka:
#  client:
#    fetch-registry: true
#    service-url:
#      default: http://localhost:8761/eureka
#  instance:
#    lease-expiration-duration-in-seconds: 2
#    lease-renewal-interval-in-seconds: 1
#
#feign:
#  hystrix:
#    enabled: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream