CREATE SEQUENCE CUST_ID_SEQ
START WITH 10000
INCREMENT BY 1
NOCYCLE;
CREATE SEQUENCE ACC_ID_SEQ
START WITH 320000
INCREMENT BY 1
NOCYCLE;
CREATE TABLE B_ACCOUNT(
A_ID NUMBER CONSTRAINT PK_B_ACC PRIMARY KEY,
C_AMOUNT NUMBER(12,2),
S_AMOUNT NUMBER(12,2)
);
CREATE TABLE CUSTOMER(
C_ID NUMBER PRIMARY KEY,
A_ID NUMBER CONSTRAINT FK_CUST_B_ACC REFERENCES B_ACCOUNT,
F_NAME VARCHAR2(15),
L_NAME VARCHAR2(18),
EMAIL VARCHAR2(40) UNIQUE,
PASSWD VARCHAR2(30)
);

CREATE OR REPLACE PROCEDURE CREATECUS(FNAME IN CUSTOMER.F_NAME%TYPE, LNAME IN CUSTOMER.L_NAME%TYPE, EML IN CUSTOMER.EMAIL%TYPE, 
PW IN CUSTOMER.PASSWD%TYPE, ACCID IN B_ACCOUNT.A_ID%TYPE)
IS
CUSID NUMBER := CUST_ID_SEQ.NEXTVAL;
BEGIN
INSERT INTO CUSTOMER VALUES(CUSID,ACCID,FNAME,LNAME,EML,PW);
COMMIT;
END CREATECUS;
/
CREATE OR REPLACE PROCEDURE CREATEACC(NACCNUM OUT B_ACCOUNT.A_ID%TYPE)
IS
ACCNUM B_ACCOUNT.A_ID%TYPE := ACC_ID_SEQ.NEXTVAL;
S_CHECK B_ACCOUNT.C_AMOUNT%TYPE := 0;
S_SAVE B_ACCOUNT.S_AMOUNT%TYPE := 0;
BEGIN
NACCNUM := ACCNUM;
INSERT INTO B_ACCOUNT VALUES (ACCNUM,S_CHECK,S_SAVE);
COMMIT;
END CREATEACC;
/
commit;
SELECT * FROM B_ACCOUNT;
SELECT * FROM CUSTOMER;

DECLARE
--NACCN B_ACCOUNT.A_ID%TYPE
BEGIN
--CREATEACC(NACCN); WOULD CREATE  NEW ACCOUNT AND PUT ITS A_ID INTO NACCN
CREATECUS('Elizabeth','Shriver','LIZ@AOL.COM','P4SSW0RD',320000);--COULD SWAP THE LAST VALUE WITH NACCN IF WE WERE CREATING AN ACCOUNT USING A NEW A_ID
END;
/
select * from b_account;
select * from CUSTOMER;
--DROP TABLE B_ACCOUNT;
--DROP TABLE CUSTOMER;