--CREATE A TABLE WITH USERS THAT WILL HAVE
CREATE TABLE USERS_TABLE(
    USER_ID NUMBER(5) PRIMARY KEY,
    USERNAME VARCHAR2(25),
    USER_PW VARCHAR2(25),
    ACCOUNT_ID NUMBER(5) 
);

CREATE TABLE ACCOUNTS(
    ACCOUNT_ID NUMBER(5) PRIMARY KEY CONSTRAINT FK_BANKACCOUNT_ID REFERENCES USERS_TABLE,
    ACCOUNT_TYPE VARCHAR2(25),
    ACCOUNT_BALANCE NUMBER(10,2)
);

DROP TABLE ACCOUNTS;
DROP TABLE USERS_TABLE;

CREATE OR REPLACE PROCEDURE CHANGE_BALANCE(INPUT_ID IN ACCOUNTS.ACCOUNT_ID%TYPE, BALANCE IN ACCOUNTS.ACCOUNT_BALANCE%TYPE)
IS
BEGIN
    --ADD BALANCE CHANGE VALUE TO THE RIGHT ACCOUNT    
    UPDATE ACCOUNTS
    SET ACCOUNT_BALANCE = ACCOUNT_BALANCE + BALANCE
    WHERE ACCOUNT_ID = INPUT_ID;
    COMMIT;
END;
/

BEGIN
    CHANGE_BALANCE(2, -500);
END;
/