server:
  port: 8765

spring:
  application:
    name: gateway-server
    
zuul:
  routes:
    reimbursement:
      path: /reimbursements/**
      serviceId: reimbursment-service
      strip-prefix: false
    employee:
      path: /employees/**
      serviceId: employee-service
      strip-prefix: false