CREATE TABLE ACCOUNT_HOLDER (
    USERNAME VARCHAR2(20) PRIMARY KEY NOT NULL,
    USER_PASSWORD VARCHAR2(60) NOT NULL,
    FIRSTNAME VARCHAR2(80),
    LASTNAME VARCHAR2(80)
);

CREATE TABLE BANK_ACCOUNT (
    ACCOUNTID NUMBER(10) PRIMARY KEY NOT NULL,
    ACCOUNTBALANCE NUMBER(24, 2) NOT NULL,
    CHECKING_OR_SAVINGS VARCHAR(80) NOT NULL
);



CREATE TABLE USER_ACCOUNT (
    USERNAME VARCHAR2(20) NOT NULL,
    ACCOUNTID NUMBER(10) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES ACCOUNT_HOLDER (USERNAME),
    FOREIGN KEY (ACCOUNTID) REFERENCES BANK_ACCOUNT (ACCOUNTID)
);


commit;

select BANK_ACCOUNT.ACCOUNTID,BANK_ACCOUNT.ACCOUNTBALANCE,BANK_ACCOUNT.CHECKING_OR_SAVINGS from BANK_ACCOUNT join USER_ACCOUNT on BANK_ACCOUNT.ACCOUNTID = USER_ACCOUNT.ACCOUNTID where USER_ACCOUNT.USERNAME ='user';