/*2.1 SELECT*/
SELECT * FROM CHINOOK.EMPLOYEE;
SELECT * FROM CHINOOK.EMPLOYEE  WHERE LASTNAME = 'King';
SELECT * FROM CHINOOK.EMPLOYEE  WHERE FIRSTNAME= 'Andrew';
SELECT * FROM CHINOOK.ALBUM ORDER BY title DESC; 
SELECT CUSTOMER.FIRSTNAME,CUSTOMER.CITY FROM CHINOOK.CUSTOMER ORDER BY city ASC;
SELECT * FROM CHINOOK.INVOICE WHERE billingaddress LIKE 'T%';
/*2.3 INSERT INTO*/
INSERT INTO CHINOOK.GENRE VALUES (26,'WORLD');
INSERT INTO CHINOOK.GENRE VALUES (27,'Rap');
INSERT INTO CHINOOK.EMPLOYEE VALUES (9,'John','Niel','IT Admin',null,'14-FEB-88','18-AUG-07', '11540 Sheridan Ave NW','Chicago',	'IL', 'USA', '60630','+1 (773) 468-9872','+1 (773) 468-9873','johnniel@chinookcorp.com');
INSERT INTO CHINOOK.EMPLOYEE VALUES (10,'James','Caplan','IT Network','','19-NOV-79','19-JAN-05', '4014 Pulaski Ave NS','Chicago',	'IL', 'USA', '60640','+1 (312) 555-7072','+1 (312) 555-7073','jamesCaplan@chinookcorp.com');
INSERT INTO CHINOOK.CUSTOMER VALUES (60,'Nour','Deen','Yahoo Inc.','30670 Drive Circle','San Diago','CA','USA','95001','+1 (408) 966-8700','+1 (408) 966-8701','NourDeen@yahoo.com',4);
INSERT INTO CHINOOK.CUSTOMER VALUES (61,'Aicha','Gapaeva','Atos Inc.','11234 Factory Ave','Phoenix','AZ','USA','87901','+1 (480) 933-8902','+1 (480) 933-8903','AichaGapaeva@atos.com',2);
/*2.4 UPDATE*/
UPDATE CHINOOK.CUSTOMER SET FIRSTNAME = 'Robert', LASTNAME= 'Walter' WHERE LASTNAME = 'Mitchell';
UPDATE CHINOOK.ARTIST SET NAME = 'CCR' WHERE NAME = 'Creedence Clearwater Revival';
/*3.0 Joins*/
/*3.1 INNER*/
SELECT CUSTOMER.FIRSTNAME,CUSTOMER.LASTNAME,INVOICE.INVOICEID FROM CHINOOK.INVOICE INNER JOIN CHINOOK.CUSTOMER ON CUSTOMER.CUSTOMERID=INVOICE.CUSTOMERID;
/*3.2 OUTER*/
SELECT CUSTOMER.FIRSTNAME,CUSTOMER.LASTNAME, INVOICE.INVOICEID,INVOICE.TOTAL FROM CHINOOK.INVOICE FULL OUTER JOIN CHINOOK.CUSTOMER ON CUSTOMER.CUSTOMERID=INVOICE.CUSTOMERID;
/*3.3 RIGHT*/
SELECT ARTIST.NAME,ALBUM.TITLE FROM CHINOOK.ALBUM RIGHT JOIN CHINOOK.ARTIST ON ARTIST.ARTISTID=ALBUM.ARTISTID;
--3.4 CROSS--
SELECT ARTIST.*,ALBUM.* FROM CHINOOK.ALBUM CROSS JOIN CHINOOK.ARTIST ORDER BY ARTIST.NAME ASC;
--3.5 SELF--
SELECT EMPLOYEE.LASTNAME,EMPLOYEE.FIRSTNAME,EMPLOYEE.REPORTSTO
FROM CHINOOK.EMPLOYEE ;
--3.6 Joined Queries--
--A--
SELECT CONCAT (CUSTOMER.FIRSTNAME,CONCAT(' ',CUSTOMER.LASTNAME)) AS FULLNAME, SUM(INVOICE.TOTAL) AS TOTAL
FROM CHINOOK.INVOICE JOIN CHINOOK.CUSTOMER 
ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID 
group by CONCAT (CUSTOMER.FIRSTNAME,CONCAT(' ',CUSTOMER.LASTNAME));
--B--
SELECT CONCAT (EMPLOYEE.FIRSTNAME,CONCAT(' ',EMPLOYEE.LASTNAME)) AS FULLNAME, COUNT(CUSTOMER.SUPPORTREPID) AS NUMBER_OF_INVOICES
FROM CHINOOK.CUSTOMER
INNER JOIN CHINOOK.INVOICE
ON INVOICE.CUSTOMERID = CUSTOMER.CUSTOMERID 
INNER JOIN CHINOOK.EMPLOYEE
ON CUSTOMER.SUPPORTREPID = EMPLOYEE.EMPLOYEEID
GROUP BY  CONCAT (EMPLOYEE.FIRSTNAME,CONCAT(' ',EMPLOYEE.LASTNAME)) ORDER BY NUMBER_OF_INVOICES DESC
FETCH FIRST ROW ONLY;
--C--
SELECT CHINOOK.GENRE.NAME, COUNT(INVOICELINE.INVOICEID) AS NUMBER_OF_PURCHASES
FROM CHINOOK.TRACK
INNER JOIN CHINOOK.INVOICELINE
ON TRACK.TRACKID = INVOICELINE.TRACKID 
INNER JOIN CHINOOK.GENRE
ON TRACK.GENREID = GENRE.GENREID
GROUP BY GENRE.NAME ORDER BY NUMBER_OF_PURCHASES DESC;
COMMIT
