server:
  port: 8765

spring:
  application:
    name: gateway-server

zuul:
  routes:
    reimbursements:
      path: /reimbursements/**
      serviceId: reimbursement-service
      strip-prefix: false
    employees:
      path: /employees/**
      service-id: employee-service
      strip-prefix: false