--CREATE A TABLE WITH USERS THAT WILL HAVE
CREATE TABLE USERS_TABLE(
    USER_ID NUMBER(5) PRIMARY KEY,
    USERNAME VARCHAR2(25),
    USER_PW VARCHAR2(25),
    ACCOUNT_ID NUMBER(5) CONSTRAINT FK_BANKACCOUNT_ID REFERENCES ACCOUNTS
);

CREATE TABLE ACCOUNTS(
    ACCOUNT_ID NUMBER(5) PRIMARY KEY,
    ACCOUNT_TYPE VARCHAR2(25),
    ACCCOUNT_BALANCE NUMBER(10,2)
);

DROP TABLE ACCOUNTS;
DROP TABLE USERS_TABLE;

CREATE OR REPLACE PROCEDURE CHANGE_BALANCE(INPUT_ID USERS_TABLE.USERS_ID%TYPE, BALANCE ACCOUNTS.ACCOUNT_BALANCE%TYPE)
IS
    ACCT_BALANCE  ACCOUNTS.ACCOUNT_BALANCE%TYPE;
BEGIN
    --GET ACCOUNT BUDGET
    SELECT ACCOUNT_BALANCE INTO ACCT_BALANCE
    FROM ACCOUNTS
    WHERE ACCOUNT_ID = 
        (SELECT ACCOUNT_ID AS ACCT_ID
        FROM USERS_TABLE U
        WHERE U.USER_ID = INPUT_ID);
    --ADD BALANCE CHANGE VALUE TO THE RIGHT ACCOUNT    
    UPDATE ACCOUNTS
    SET ACCOUNT_BALANCE = ACCOUNT_BALANCE + BALANCE
    WHERE ACCOUNT_ID = 
        (SELECT ACCOUNT_ID AS ACCT_ID
        FROM USERS_TABLE U
        WHERE U.USER_ID = INPUT_ID);
END;
/