-- CREATE A MEMBERS TABLE --
CREATE TABLE MEMBER_ACCOUNT(

    ACCOUNT_NUMBER NUMBER(8) CONSTRAINT PK_ACCTNUM PRIMARY KEY,
    USER_FIRSTNAME VARCHAR2(30),
    USER_LASTNAME VARCHAR2(50),
    USER_USERNAME VARCHAR2(50),
    USER_PASSWORD VARCHAR2(30),
    USER_EMAIL VARCHAR2(50)
    
);

-- CREATE AN ACCOUNT BALANCE TABLE THE USES THE ACCOUNT NUMBER AS THE FOREIGN KEY
CREATE TABLE ACCOUNT_TABLE(
    
    ACCOUNT_NUMBER NUMBER(8) CONSTRAINT FK_MEM_ACCT REFERENCES MEMBER_ACCOUNT,
    ACCOUNT_TYPE VARCHAR2(30),
    ACCOUNT_BALANCE NUMBER(8,2)
    
);

SAVEPOINT TABLES_CREATED;
COMMIT;


-- CREATE DEPOSIT PROCEDURE --
CREATE OR REPLACE PROCEDURE MAKE_DEPOSIT(ACCT IN ACCOUNT_TABLE.ACCOUNT_NUMBER%TYPE, ACCT_TPE IN ACCOUNT_TABLE.ACCOUNT_TYPE%TYPE, DEPOSIT IN ACCOUNT_TABLE.ACCOUNT_BALANCE%TYPE)
IS
BEGIN
    UPDATE ACCOUNT_TABLE
    SET ACCOUNT_BALANCE = ACCOUNT_BALANCE + DEPOSIT
    WHERE ACCOUNT_TYPE = ACCT_TPE AND ACCOUNT_NUMBER = ACCT;
END;
/

COMMIT;

BEGIN
    MAKE_DEPOSIT(17263238, 'Savings', 99.00);
    MAKE_DEPOSIT(17263238, 'Checkings', 150.75); 
END;
/

-- CREATE WITHDRAWAL PROCEDURE --
CREATE OR REPLACE PROCEDURE MAKE_WITHDRAWAL(ACCT IN ACCOUNT_TABLE.ACCOUNT_NUMBER%TYPE, ACCT_TPE IN ACCOUNT_TABLE.ACCOUNT_TYPE%TYPE, WITHDRAWAL IN ACCOUNT_TABLE.ACCOUNT_BALANCE%TYPE)
IS
    USER_BALANCE ACCOUNT_TABLE.ACCOUNT_BALANCE%TYPE;
BEGIN
    SELECT ACCOUNT_BALANCE INTO USER_BALANCE
    FROM ACCOUNT_TABLE
    WHERE ACCOUNT_NUMBER = ACCT AND ACCOUNT_TYPE = ACCT_TPE;
    
    IF(USER_BALANCE - WITHDRAWAL) < 0 THEN
    -- WITHDRAWAL AMOUNT TOO LARGE--
    DBMS_OUTPUT.PUT_LINE('INSUFFICIENT FUNDS!');
    ELSE
        UPDATE ACCOUNT_TABLE
        SET ACCOUNT_BALANCE = (USER_BALANCE - WITHDRAWAL)
        WHERE ACCOUNT_NUMBER = ACCT AND ACCOUNT_TYPE = ACCT_TPE;
    END IF;
END;
/

COMMIT;

BEGIN
    MAKE_WITHDRAWAL(17263238, 'Checkings', 2575.50);
END;
/

SET SERVEROUTPUT ON;

-- VIEW BALANCE PROCEDURE --
CREATE OR REPLACE PROCEDURE VIEW_BALANCE(ACCT IN ACCOUNT_TABLE.ACCOUNT_NUMBER%TYPE, ACCT_TPE IN ACCOUNT_TABLE.ACCOUNT_TYPE%TYPE)
IS
    USER_BALANCE ACCOUNT_TABLE.ACCOUNT_BALANCE%TYPE;
BEGIN
    SELECT ACCOUNT_BALANCE INTO USER_BALANCE
    FROM ACCOUNT_TABLE
    WHERE ACCOUNT_NUMBER = ACCT AND ACCOUNT_TYPE = ACCT_TPE;
    DBMS_OUTPUT.PUT_LINE('ACCOUNT BALANCE: $' || USER_BALANCE);
END;
/

BEGIN
    VIEW_BALANCE(17263238, 'Checkings');
END;
/

SAVEPOINT BASICTRANSACTIONSCOMPLETE;
COMMIT;

-- CREATE A STORED PROCEDURE TO COMMIT CHANGES TO THE DB --



    