-- CREATE A MEMBERS TABLE --
CREATE TABLE MEMBER_ACCOUNT(

    ACCOUNT_NUMBER NUMBER(8) PRIMARY KEY,
    USER_FIRSTNAME VARCHAR2(30),
    USER_LASTNAME VARCHAR2(50),
    USER_USERNAME VARCHAR2(50),
    USER_PASSWORD VARCHAR2(30)
    
);

-- CREATE AN ACCOUNT BALANCE TABLE THE USES THE ACCOUNT NUMBER AS THE FOREIGN KEY
CREATE TABLE ACCOUNT_TABLE(

    ACCOUNT_NUMBER NUMBER(8) PRIMARY KEY REFERENCES MEMBER_ACCOUNT,
    ACCOUNT_TYPE VARCHAR2(30),
    ACCOUNT_BALANCE NUMBER(8,2)
    
);

SAVEPOINT TABLES_CREATED;
COMMIT;

ALTER TABLE MEMBER_ACCOUNT
ADD USER_EMAIL VARCHAR2(50);

SAVEPOINT ADDED_EMAIL;
COMMIT;


-- CREATE DEPOSIT PROCEDURE --
CREATE OR REPLACE PROCEDURE MAKE_DEPOSIT(ACCT IN ACCOUNT_TABLE.ACCOUNT_NUMBER%TYPE, DEPOSIT IN ACCOUNT_TABLE.ACCOUNT_BALANCE%TYPE)
IS
BEGIN
    UPDATE ACCOUNT_TABLE
    SET ACCOUNT_BALANCE = ACCOUNT_BALANCE + DEPOSIT
    WHERE ACCOUNT_NUMBER = ACCT;
END;
/

BEGIN
    MAKE_DEPOSIT(74873389, 2575.50);
END;
/

-- CREATE WITHDRAWAL PROCEDURE --
CREATE OR REPLACE PROCEDURE MAKE_WITHDRAWAL(ACCT IN ACCOUNT_TABLE.ACCOUNT_NUMBER%TYPE, WITHDRAWAL IN ACCOUNT_TABLE.ACCOUNT_BALANCE%TYPE)
IS
    USER_BALANCE ACCOUNT_TABLE.ACCOUNT_BALANCE%TYPE;
BEGIN
    SELECT ACCOUNT_BALANCE INTO USER_BALANCE
    FROM ACCOUNT_TABLE
    WHERE ACCOUNT_NUMBER = ACCT;
    
    IF(USER_BALANCE - WITHDRAWAL) < 0 THEN
    -- WITHDRAWAL AMOUNT TOO LARGE--
    DBMS_OUTPUT.PUT_LINE('INSUFFICIENT FUNDS!');
    ELSE
        UPDATE ACCOUNT_TABLE
        SET ACCOUNT_BALANCE = USER_BALANCE - WITHDRAWAL
        WHERE ACCOUNT_NUMBER = ACCT;
    END IF;
END;
/

BEGIN
    MAKE_WITHDRAWAL(74873389, 2575.50);
END;
/


SAVEPOINT BASICTRANSACTIONSCOMPLETE;
COMMIT;


    