server:
  port: 8765

spring:
  application:
    name: gateway-server
    
zuul:
  routes:
    account:
      path: /employees/**
      serviceId: employee-service
      strip-prefix: false
    customer:
      path: /reimburstments/**
      serviceId: reimburstment-service
      strip-prefix: false
      