--------------------------------------------------------
--  File created - Wednesday-April-03-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."ACCOUNT" 
   (	"ID" NUMBER(10,0), 
	"BALANCE" FLOAT(126), 
	"TYPE" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."ACCOUNTS" 
   (	"ACC_NUM" NUMBER(10,0), 
	"MEM_NUM" NUMBER(5,0), 
	"ACC_TYPE" VARCHAR2(10 BYTE), 
	"BALANCE" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANK_CLIENTS
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."BANK_CLIENTS" 
   (	"MEM_NUM" NUMBER(*,0), 
	"FIRSTNAME" VARCHAR2(25 BYTE), 
	"LASTNAME" VARCHAR2(25 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"USERNAME" VARCHAR2(25 BYTE), 
	"PASSWORD" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAT
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."CAT" 
   (	"C_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"COLOR" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."DEPARTMENT" 
   (	"DEPT_ID" NUMBER(5,0), 
	"DEPT_NAME" VARCHAR2(50 BYTE), 
	"MONTHLY_BUDGET" NUMBER(7,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."EMPLOYEE" 
   (	"EMP_ID" NUMBER(5,0), 
	"EMP_NAME" VARCHAR2(50 BYTE), 
	"BIRTHDAY" DATE, 
	"MONTHLY_SALARY" NUMBER(7,2), 
	"POSITION" VARCHAR2(20 BYTE), 
	"MANAGER_ID" NUMBER(5,0), 
	"DEPT_ID" NUMBER(5,0), 
	"HIRE_DATE" DATE, 
	"LOCATION_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE2
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."EMPLOYEE2" 
   (	"EMP_ID" NUMBER(5,0), 
	"EMP_NAME" VARCHAR2(50 BYTE), 
	"MONTHLY_SALARY" NUMBER(7,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."EMPLOYEES" 
   (	"EMP_ID" NUMBER(4,0), 
	"EMP_FIRST" VARCHAR2(25 BYTE), 
	"EMP_LAST" VARCHAR2(25 BYTE), 
	"EMP_USER" VARCHAR2(15 BYTE), 
	"EMP_PASS" VARCHAR2(15 BYTE), 
	"IS_MANA" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATIONS
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."LOCATIONS" 
   (	"LOCATION_ID" NUMBER(5,0), 
	"STREET" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(2 BYTE), 
	"ZIPCODE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REIMBURSEMENTS
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."REIMBURSEMENTS" 
   (	"REIM_ID" NUMBER(7,0), 
	"REIM_NAME" VARCHAR2(28 BYTE), 
	"REQUESTER" NUMBER(4,0), 
	"AMOUNT" NUMBER(8,2), 
	"STATUS" VARCHAR2(10 BYTE) DEFAULT 'PENDING', 
	"RESOLVED_BY" NUMBER(4,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "AUGUST112641"."USER_ACCOUNT" 
   (	"USER_ID" NUMBER(10,0), 
	"ACCOUNT_ID" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005414
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUGUST112641"."SYS_C005414" ON "AUGUST112641"."ACCOUNT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005218
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUGUST112641"."SYS_C005218" ON "AUGUST112641"."ACCOUNTS" ("ACC_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005202
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUGUST112641"."SYS_C005202" ON "AUGUST112641"."BANK_CLIENTS" ("MEM_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005361
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUGUST112641"."SYS_C005361" ON "AUGUST112641"."CAT" ("C_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DEPT
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUGUST112641"."PK_DEPT" ON "AUGUST112641"."DEPARTMENT" ("DEPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005101
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUGUST112641"."SYS_C005101" ON "AUGUST112641"."EMPLOYEE" ("EMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005264
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUGUST112641"."SYS_C005264" ON "AUGUST112641"."EMPLOYEES" ("EMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUGUST112641"."UNIQUE_USER" ON "AUGUST112641"."EMPLOYEES" ("EMP_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LOCATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUGUST112641"."PK_LOCATIONS" ON "AUGUST112641"."LOCATIONS" ("LOCATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005280
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUGUST112641"."SYS_C005280" ON "AUGUST112641"."REIMBURSEMENTS" ("REIM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ACC_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AUGUST112641"."ACC_ID" 
   before insert on "AUGUST112641"."ACCOUNTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ACC_NUM" is null then 
         select ACC_INCREMENT.nextval into :NEW."ACC_NUM" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "AUGUST112641"."ACC_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENTS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AUGUST112641"."CLIENTS_ID" 
   before insert on "AUGUST112641"."BANK_CLIENTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."MEM_NUM" is null then 
         select ID_INCREMENT.nextval into :NEW."MEM_NUM" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "AUGUST112641"."CLIENTS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMP_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AUGUST112641"."EMP_ID" 
   before insert on "AUGUST112641"."EMPLOYEES" 
   for each row 
begin  
   if inserting then 
      if :NEW."EMP_ID" is null then 
         select EMP_ID_INCRE.nextval into :NEW."EMP_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "AUGUST112641"."EMP_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REIM_ID_AUTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AUGUST112641"."REIM_ID_AUTO" 
   before insert on "AUGUST112641"."REIMBURSEMENTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."REIM_ID" is null then 
         select REIM_INCRE.nextval into :NEW."REIM_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "AUGUST112641"."REIM_ID_AUTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DATE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AUGUST112641"."DATE_INSERT" 
BEFORE 
INSERT
ON REIMBURSEMENTS
FOR EACH ROW 
BEGIN UPDATE
SET DATE_SUB = TIMESTAMP; 
END;

/
ALTER TRIGGER "AUGUST112641"."DATE_INSERT" DISABLE;
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."ACCOUNT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AUGUST112641"."ACCOUNT" MODIFY ("BALANCE" NOT NULL ENABLE);
  ALTER TABLE "AUGUST112641"."ACCOUNT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."ACCOUNTS" ADD CONSTRAINT "NON_NEGATIVE" CHECK (BALANCE >0) ENABLE;
  ALTER TABLE "AUGUST112641"."ACCOUNTS" ADD PRIMARY KEY ("ACC_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BANK_CLIENTS
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."BANK_CLIENTS" ADD PRIMARY KEY ("MEM_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAT
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."CAT" ADD PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AUGUST112641"."CAT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AUGUST112641"."CAT" MODIFY ("C_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."DEPARTMENT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY ("DEPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."EMPLOYEE" ADD PRIMARY KEY ("EMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AUGUST112641"."EMPLOYEE" MODIFY ("MONTHLY_SALARY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE2
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."EMPLOYEE2" MODIFY ("MONTHLY_SALARY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."EMPLOYEES" ADD CONSTRAINT "UNIQUE_USER" UNIQUE ("EMP_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AUGUST112641"."EMPLOYEES" ADD PRIMARY KEY ("EMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATIONS
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."LOCATIONS" ADD CONSTRAINT "PK_LOCATIONS" PRIMARY KEY ("LOCATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REIMBURSEMENTS
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."REIMBURSEMENTS" ADD PRIMARY KEY ("REIM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."USER_ACCOUNT" MODIFY ("ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "AUGUST112641"."USER_ACCOUNT" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."ACCOUNTS" ADD FOREIGN KEY ("MEM_NUM")
	  REFERENCES "AUGUST112641"."BANK_CLIENTS" ("MEM_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."EMPLOYEE" ADD CONSTRAINT "FK_EMP_DEPT" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "AUGUST112641"."DEPARTMENT" ("DEPT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AUGUST112641"."EMPLOYEE" ADD CONSTRAINT "FK_EMP_LOCATION" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "AUGUST112641"."LOCATIONS" ("LOCATION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REIMBURSEMENTS
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."REIMBURSEMENTS" ADD CONSTRAINT "RESOLVED_BY" FOREIGN KEY ("RESOLVED_BY")
	  REFERENCES "AUGUST112641"."EMPLOYEES" ("EMP_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "AUGUST112641"."USER_ACCOUNT" ADD CONSTRAINT "FK_1MQAQTKGDBS1DO6LODM2QQWUG" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "AUGUST112641"."ACCOUNT" ("ID") ENABLE;
