-------------
-- SQL LAB --
-------------



-- Queries and DML --

-- 2.1 SELECT --
-- a
SELECT * 
FROM EMPLOYEE;

-- b 
SELECT *
FROM EMPLOYEE
WHERE EMPLOYEE.LASTNAME = 'King';

-- c
SELECT * 
FROM EMPLOYEE
WHERE EMPLOYER.FIRSTNAME = 'Andrew' AND EMPLOYEE.REPORTSTO IS NULL;

-- d
SELECT *
FROM ALBUM
ORDER BY ALBUM.TITLE DESC;

-- e
SELECT C.FIRSTNAME
FROM CUSTOMER C
ORDER BY C.CITY ASC;

-- f
SELECT *
FROM INVOICE
WHERE BILLINGADDRESS LIKE 'T%';

SAVEPOINT SELECTDONE;
COMMIT;

-- 2.2 INSERT INTO --
-- a
INSERT INTO GENRE VALUES (26, 'Punk Rock');
INSERT INTO GENRE VALUES (27, 'Crossover');

 -- b
 
INSERT INTO EMPLOYEE VALUES (9, 'Krabs', 'Eugene', 'Sales Director', Null, TO_DATE('1943-11-17 00:00:00','yyyy-mm-dd hh24:mi:ss'), TO_DATE('1999-5-1 00:00:00','yyyy-mm-dd hh24:mi:ss'), '247 Bikini Bottom SW', 'Calgary', 'AB', 'Canada', 'T2P 2T3', '+1 (403) 484-1638', '+1 (403) 484-3912', 'krustykrab@chinookcorp.com');
INSERT INTO EMPLOYEE VALUES (10, 'Shape', 'Bob', 'Maintenance', 9, TO_DATE('1965-5-14 00:00:00','yyyy-mm-dd hh24:mi:ss'), TO_DATE('1995-6-1 00:00:00','yyyy-mm-dd hh24:mi:ss'), '782 Bikini Bottom W', 'Calgary', 'AB', 'Canada', 'T2P 2T3', '+1 (403) 288-2106', '+1 (403) 288-8943', 'ilovekrabbypatties@chinookcorp.com');

-- c

INSERT INTO INVOICE VALUES (413, 17, TO_DATE('2011-6-27 00:00:00','yyyy-mm-dd hh24:mi:ss'), '3245 82 Ave', 'Portland', 'OR', 'USA', '97299', 24.59);
INSERT INTO INVOICE VALUES (414, 44, TO_DATE('2004-2-3 00:00:00','yyyy-mm-dd hh24:mi:ss'), '1 Patriot Drive', 'Foxborough', 'MA', 'USA', '02035', 678.98);

SAVEPOINT INSERTDONE;
COMMIT;

-- 2.3 UPDATE --
-- a
UPDATE CUSTOMER
SET FIRSTNAME = 'Robert', LASTNAME = 'Walter'
WHERE FIRSTNAME = 'Aaron' AND LASTNAME = 'Mitchell';

UPDATE ARTIST
SET NAME = 'CCR'
WHERE NAME = 'Creedence Clearwater Revival';

SAVEPOINT UPDATESDONE;
COMMIT;

-- Joins --
-- 3.1 INNER JOIN --
SELECT C.FIRSTNAME AS FIRST_NAME, C.LASTNAME AS LAST_NAME, I.INVOICEID AS INVOICE_ID
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUSTOMERID = I.CUSTOMERID;
COMMIT;

-- 3.2 OUTER JOIN --
SELECT C.CUSTOMERID AS CUSTOMER_ID,C.FIRSTNAME AS FIRST_NAME, C.LASTNAME AS LAST_NAME, I.INVOICEID AS INVOICE_ID, I.TOTAL AS TOTAL
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUSTOMERID = I.CUSTOMERID;
COMMIT;

-- 3.3 RIGHT JOIN --
SELECT AL.TITLE AS ALBUM, AR.NAME AS ARTIST
FROM ALBUM AL
RIGHT JOIN ARTIST AR
ON AR.ARTISTID = AL.ARTISTID;
COMMIT;

-- 3.4 CROSS JOIN --
SELECT AL.TITLE AS ALBUM, AR.NAME AS ARTIST
FROM ALBUM AL
RIGHT JOIN ARTIST AR
ON AR.ARTISTID = AL.ARTISTID
ORDER BY AR.NAME ASC;
COMMIT;

-- 3.5 SELF JOIN --
SELECT E.EMPLOYEEID AS EMPLOYEE_ID, CONCAT(E.FIRSTNAME, CONCAT(' ', E.LASTNAME)) AS EMPLOYEE, CONCAT(M.FIRSTNAME, CONCAT(' ', M.LASTNAME)) AS MANAGER
FROM EMPLOYEE E, EMPLOYEE M
WHERE E.REPORTSTO = M.EMPLOYEEID
ORDER BY E.EMPLOYEEID ASC;
COMMIT;

-- 3.6 JOINED QUERIES --
-- a
SELECT C.CUSTOMERID AS ID, CONCAT(C.FIRSTNAME, CONCAT(' ', C.LASTNAME)) AS FULL_NAME, SUM(I.TOTAL) AS TOTAL
FROM CUSTOMER C
LEFT JOIN INVOICE I
ON C.CUSTOMERID = I.CUSTOMERID
GROUP BY C.CUSTOMERID, CONCAT(C.FIRSTNAME, CONCAT(' ', C.LASTNAME))
ORDER BY C.CUSTOMERID ASC;
COMMIT;

-- b
SELECT *
FROM
    (SELECT CONCAT(E.FIRSTNAME, CONCAT(' ', E.LASTNAME)) AS EMPLOYEE, SUM(I.INVOICEID) AS TOTAL_SALES
    FROM EMPLOYEE E  
    JOIN CUSTOMER C
    ON C.SUPPORTREPID = E.EMPLOYEEID
    JOIN INVOICE I
    ON I.CUSTOMERID = C.CUSTOMERID
    GROUP BY CONCAT(E.FIRSTNAME, CONCAT(' ', E.LASTNAME))
    ORDER BY SUM(I.INVOICEID) DESC)
WHERE ROWNUM = 1;

COMMIT;

-- c
SELECT G.NAME AS GENRE, SUM(I.INVOICEID) AS TOTAL_SALES
FROM GENRE G 
JOIN TRACK T
ON G.GENREID = T.GENREID
JOIN INVOICELINE IL
ON IL.TRACKID = T.TRACKID
JOIN INVOICE I
ON I.INVOICEID = IL.INVOICEID
GROUP BY G.NAME
ORDER BY SUM(I.INVOICEID) DESC;

SAVEPOINT JOINSDONE;
COMMIT;

