INSERT INTO INVOICE VALUES(11, DATE '2019-02-27', NULL, 234.67, 'STUFF');
INSERT INTO INVOICE VALUES(16, DATE '2019-02-26', NULL, 237.67, 'SOME STUFF');
INSERT INTO INVOICE VALUES(17, DATE '2019-02-25', NULL, 436.67, 'MORE STUFF');
INSERT INTO INVOICE VALUES(18, DATE '2019-02-27', NULL, 743.67, 'ALL STUFF');

INSERT INTO CUSTOMER VALUES(8, 'SANDRA MEYERS', 'S.MEYER@GMAIL.COM', '123 PANIC DRIVE');
INSERT INTO CUSTOMER VALUES(9, 'SANDRO ALMENDARIZ', 'S.ALMENDARIZ@GMAIL.COM', '654 OCE ROAD');
INSERT INTO CUSTOMER VALUES(10, 'BOGGART 33', 'B.33@GMAIL.COM', '33 MY DRIVE');

SELECT INVOICE.CUSTOMER_ID AS INVOICE, CUSTOMER.NAME AS CUSTOMER
FROM INVOICE
JOIN CUSTOMER
ON INVOICE.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID;

SELECT INVOICE.CUSTOMER_ID AS INVOICE, CUSTOMER.NAME AS CUSTOMER
FROM INVOICE
RIGHT OUTER  JOIN CUSTOMER
ON INVOICE.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID;

SELECT INVOICE.CUSTOMER_ID AS INVOICE, CUSTOMER.NAME AS CUSTOMER
FROM CUSTOMER
LEFT OUTER  JOIN INVOICE
ON INVOICE.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID;

SELECT I.PRICE
FROM INVOICE I
UNION
SELECT NAME
FROM CUSTOMER 
ON  I.CUSTOMER_ID = CUSTUMER.CUSTOMER_ID
GROUP_BY I.INVOICE_ID;