INSERT INTO BANK_CLIENTS VALUES(1,'Javier', 'Rodriguez', 'August112641@gmail.com');
INSERT INTO ACCOUNTS VALUES(1, 'Checking', 50);

SELECT USERNAME, PASSWORD FROM BANK_CLIENTS;


--CREATE OR REPLACE  TRIGGER INCREMENT_TRIGGER 
--BEFORE INSERT ON BANK_CLIENTS 
--FOR EACH ROW
--
--BEGIN 
--IF ACC_NUM IS NULL THEN
--SELECT ID_INCREMENT.NEXTVAL
--INTO ACC_NUM
--FROM DUAL;
--END IF;
--END;
--/

CREATE OR REPLACE PROCEDURE CREDENTIALS
AS 
BEGIN 
SELECT USERNAME, PASSWORD INTO DUAL
FROM BANK_CLIENTS;
END;
/

SELECT USERNAME, PASSWORD FROM BANK_CLIENTS;



SELECT * FROM BANK_CLIENTS WHERE USERNAME = 'August112641' AND PASSWORD = 'Jar1126';


--SELECT (FIRSTNAME||' '|| LASTNAME) FROM BANK_CLIENTS WHERE USERNAME='August112641' AND PASSWORD = 'Jar1126';

CREATE OR REPLACE TRIGGER ACCOUNT_CREATION 
AFTER INSERT ON BANK_CLIENTS 
BEGIN
  INSERT INTO ACCOUNTS VALUES ((select ACC_NUM from Bank_clients), 'Checking', 0);
END;


