CREATE TABLE CLIENTS(
ADMIN_STATUS VARCHAR2(5),
CLIENT_FIRSTNAME VARCHAR2(8),
CLIENT_LASTNAME VARCHAR2(8),
CLIENT_EMAIL VARCHAR2(30),
CLIENT_ACCOUNT_NUMBER NUMBER(6) PRIMARY KEY,
CLIENT_ACCOUNT_TYPE VARCHAR2(10)
);
