create or replace trigger AUTO_Id  
   before insert on "AUGUST112641"."BANK_CLIENTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."MEM_NUM" is null then 
         select ID_INCREMENT.nextval into :NEW."MEM_NUM" from dual; 
      end if; 
   end if; 
end;
/

create or replace TRIGGER ACCOUNT_CREATION 
BEFORE INSERT ON BANK_CLIENTS 
BEGIN
  INSERT INTO ACCOUNTS VALUES (select mem_num into accounts, 'Checking', 0);
END;
/
drop trigger Auto_Id;

CREATE OR REPLACE PROCEDURE WITHDRAW (MEMBER IN ACCOUNTS.MEM_NUM%TYPE, AMO IN ACCOUNTS.BALANCE%TYPE)
IS
BEGIN
    UPDATE ACCOUNTS
    SET BALANCE = BALANCE - AMO
    WHERE MEM_NUM = MEMBER;
END;
/

   CREATE SEQUENCE  "AUGUST112641"."ID_INCREMENT"  MINVALUE 1 MAXVALUE 2000 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

INSERT INTO BANK_CLIENTS VALUES (1,'Javier', 'Rodriguez', 'August112641@gmail.com', 'August112641', 'Jar1126'); 
INSERT INTO ACCOUNTS VALUES(1, 'Checkings', 0);

begin
withdraw(1, 30);
end;
/

create or replace PROCEDURE WITHDRAW (MEMBER IN ACCOUNTS.MEM_NUM%TYPE, AMO IN ACCOUNTS.BALANCE%TYPE)
IS
BEGIN
SELECT BALANCE FROM ACCOUNTS WHERE MEM
    IF ((BALANCE -AMO)>BALANCE) THEN
    DBMS_OUTPUT.PUT_LINE('INSUFFICIENT FUNDS AVAILABLE');
    ELSE
    UPDATE ACCOUNTS
    SET BALANCE = BALANCE - AMO
    WHERE MEM_NUM = MEMBER;
    END IF;
END;
/

CREATE SEQUENCE or replace "AUGUST112641"."ACC_INCREMENT"  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1000003 CACHE 25 NOORDER  NOCYCLE  NOPARTITION ;

create or replace PROCEDURE WITHDRAW (MEMBER IN ACCOUNTS.MEM_NUM%TYPE, AMO IN ACCOUNTS.BALANCE%TYPE)
IS
BEGIN
    UPDATE ACCOUNTS
    SET BALANCE = BALANCE - AMO
    WHERE MEM_NUM = MEMBER;
END;
/

ALTER TABLE ACCOUNTS
ADD CONSTRAINT NON_NEGATIVE CHECK (BALANCE >0);


   CREATE SEQUENCE  "AUGUST112641"."ID_INCREMENT"  MINVALUE 1 MAXVALUE 2000 INCREMENT BY 1 START WITH 3 CACHE 20 ORDER  NOCYCLE  NOPARTITION ;
   CREATE SEQUENCE  "AUGUST112641"."ACC_INCREMENT"  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1000003 CACHE 25 ORDER  NOCYCLE  NOPARTITION ;


   CREATE SEQUENCE  "AUGUST112641"."ID_INCREMENT"  MINVALUE 1 MAXVALUE 2000 INCREMENT BY 1 START WITH 5 CACHE 20 ORDER  NOCYCLE  NOPARTITION ;
