server:
  port: 2333
  
spring:
  application:
    name: account-service
    
eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2